name: Build and Release Rust Project

on:
  push:
    tags:
      - 'v*'  # 仅当推送以 v 开头的标签时触发（如 v1.0.0）

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 配置 Rust 环境
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    # 3. 构建 Release 版本
    - name: Build Release
      run: cargo build --release --target x86_64-pc-windows-msvc

    # 4. 发布到 GitHub Releases
    - name: Release to GitHub
      uses: softprops/action-gh-release@v1  # 使用新版 Action（已集成文件上传）
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        files: |
          target/x86_64-pc-windows-msvc/release/ipp-sharing.exe  # 替换为你的项目名
        draft: false
        prerelease: false

    # 5. 上传构建产物（可选，保留 Artifact 供临时下载）
    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v4  # 使用新版 Artifact 上传
      with:
        name: windows-exe
        path: target/x86_64-pc-windows-msvc/release/YOUR_PROJECT_NAME.exe
        retention-days: 7  # 构建产物保留 7 天
