name: Build and Release Rust Project

on:
  push:
    branches: [ main ]  # 推送代码到 main 分支触发构建
  workflow_dispatch:    # 允许手动触发构建
  release:
    types: [ published ] # 发布 Release 时触发构建

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Build Release
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        files: |
          target/x86_64-pc-windows-msvc/release/ipp-sharing.exe
        draft: false
        prerelease: false

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: target/x86_64-pc-windows-msvc/release/ipp-sharing.exe
        retention-days: 7
