name: Rust Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Avahi dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavahi-client-dev libavahi-common-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose
